# Generated by Django 5.0.4 on 2024-04-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usercode',
            field=models.CharField(default=0, max_length=6, unique=True),
            preserve_default=False,
        ),
    ]
