# Generated by Django 5.2.3 on 2025-07-02 10:09

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePlayerLobby',
            fields=[
                ('lobby_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('coordinatesindex', models.IntegerField(default=0)),
                ('time_duration', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('points', models.IntegerField(default=0)),
                ('gamemode', models.CharField(default='world', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'singleplayer_lobbies',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleplayer.singleplayerlobby')),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
    ]
