# Generated by Django 5.0.4 on 2024-05-07 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePlayerLobby',
            fields=[
                ('lobby_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('gamemode', models.CharField(choices=[('world', 'World'), ('timelimit', 'Timelimit'), ('italy', 'Italy')], default='world', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'singleplayer_lobbies',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='singleplayer.singleplayerlobby')),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
    ]
