# Generated by Django 5.0.6 on 2024-05-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerlobby',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
