# Generated by Django 5.0.4 on 2024-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerlobby',
            name='coordinatesindex',
            field=models.IntegerField(default=0),
        ),
    ]
