# Generated by Django 5.0.4 on 2024-05-07 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singleplayer', '0002_singleplayerlobby_coordinatesindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayerlobby',
            name='time_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=300)),
        ),
    ]
