# Generated by Django 5.0.4 on 2024-05-21 16:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiPlayerLobby',
            fields=[
                ('lobby_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('gamemode', models.CharField(choices=[('world', 'World'), ('timelimit', 'Timelimit')], default='world', max_length=20)),
                ('coordinatesindex', models.IntegerField(default=0)),
                ('time_duration', models.DurationField(default=datetime.timedelta(seconds=300))),
            ],
            options={
                'db_table': 'multiplayer_lobbies',
            },
        ),
        migrations.CreateModel(
            name='LobbyUser',
            fields=[
                ('lobby_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=50)),
                ('round_finished', models.BooleanField(default=False)),
                ('points', models.IntegerField(default=0)),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplayer.multiplayerlobby')),
            ],
            options={
                'db_table': 'lobby_users',
            },
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('coordinate_id', models.AutoField(primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('lobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multiplayer.multiplayerlobby')),
            ],
            options={
                'db_table': 'multiplayer_coordinates',
            },
        ),
    ]
