# Generated by Django 5.0.4 on 2024-05-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyuser',
            name='round_distance',
            field=models.FloatField(default=0),
        ),
    ]
