# Generated by Django 5.0.4 on 2024-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0002_lobbyuser_round_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplayerlobby',
            name='rounds',
            field=models.IntegerField(default=5),
        ),
    ]
