# Generated by Django 5.0.6 on 2024-05-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0004_alter_lobbyuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobbyuser',
            name='role',
            field=models.CharField(choices=[('host', 'Host'), ('player', 'Player')], default='player', max_length=6),
        ),
    ]
