# Generated by Django 5.0.6 on 2024-05-23 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiplayer', '0005_lobbyuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplayerlobby',
            name='time_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
